# Generated by Django 5.2 on 2025-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_story', models.TextField(help_text="The story transcribed from the user's audio input.")),
                ('generated_questions', models.JSONField(help_text='A list of questions generated by the AI based on the story.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the story was recorded.')),
            ],
        ),
    ]
