from django.db import models



class Story(models.Model):
    """
    A model to store the user's narrated story and the AI-generated questions.
    """
    user_story = models.TextField(
        help_text="The story transcribed from the user's audio input."
    )
    generated_questions = models.JSONField(
        help_text="A list of questions generated by the AI based on the story."
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="The date and time the story was recorded."
    )

    def __str__(self):
        """String for representing the model object."""
        return f"Story from {self.created_at.strftime('%Y-%m-%d %H:%M')}"
